global:
  scrape_interval: 15s # 15초마다 메트릭 수집

scrape_configs:
  - job_name: 'spring-actuator' # 작업 이름
    metrics_path: '/actuator/prometheus' # 1단계에서 열어준 엔드포인트
    static_configs:
      # 'my-api-server:8080'은 docker-compose 내부에서 사용할 서비스 이름
      - targets: ['my-api-server:8080']